/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GlavnaForma.java
 *
 * Created on May 21, 2010, 10:49:31 PM
 */
package forme;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import klasaZaKomunikaciju.KlasaZaKomunikacijuKlijent;
import kontrolerKorisnickogInterfejsa.KontrolerFormeGlavna;

/**
 *
 * @author user
 */
public class FormaGlavna extends javax.swing.JFrame {

    KontrolerFormeGlavna kkifg;
    boolean povezan = false;

    /** Creates new form GlavnaForma */
    public FormaGlavna() {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        JFrame.setDefaultLookAndFeelDecorated(true);


        initComponents();
        jbPrikaziKatalog.setEnabled(false);
        jbPrikaziNarudzbenice.setEnabled(false);
        jbPrikaziRacune.setEnabled(false);
        kkifg = new KontrolerFormeGlavna();
        this.setTitle("GlAVNA FORMA");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPrikaziKatalog = new javax.swing.JButton();
        jbPrikaziNarudzbenice = new javax.swing.JButton();
        jbPrikaziRacune = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbPrikaziKatalog.setText("Katalog");
        jbPrikaziKatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrikaziKatalogActionPerformed(evt);
            }
        });

        jbPrikaziNarudzbenice.setText("Narudzbenice");
        jbPrikaziNarudzbenice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrikaziNarudzbeniceActionPerformed(evt);
            }
        });

        jbPrikaziRacune.setText("Racuni");
        jbPrikaziRacune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrikaziRacuneActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("povezi se sa serverom");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPrikaziKatalog, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jbPrikaziNarudzbenice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPrikaziRacune, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jbPrikaziKatalog)
                .addGap(31, 31, 31)
                .addComponent(jbPrikaziNarudzbenice)
                .addGap(34, 34, 34)
                .addComponent(jbPrikaziRacune)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-641)/2, (screenSize.height-262)/2, 641, 262);
    }// </editor-fold>//GEN-END:initComponents

    private void jbPrikaziKatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrikaziKatalogActionPerformed
        kkifg.prikaziKatalog(this);
    }//GEN-LAST:event_jbPrikaziKatalogActionPerformed

    private void jbPrikaziRacuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrikaziRacuneActionPerformed
        kkifg.prikaziRacune(this);
    }//GEN-LAST:event_jbPrikaziRacuneActionPerformed

    private void jbPrikaziNarudzbeniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrikaziNarudzbeniceActionPerformed
        kkifg.prikaziNarudzbenice(this);
    }//GEN-LAST:event_jbPrikaziNarudzbeniceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        KlasaZaKomunikacijuKlijent k = KlasaZaKomunikacijuKlijent.getInstance();
        if (!k.jePovezan()) {
            JOptionPane.showMessageDialog(this, "Neuspesno povezivanje sa serverom. aplikacija ce se zatvoriti");
            System.exit(0);
        }
        jbPrikaziKatalog.setEnabled(true);
        jbPrikaziRacune.setEnabled(true);
        jbPrikaziNarudzbenice.setEnabled(true);
        povezan = true;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (povezan) {
            KlasaZaKomunikacijuKlijent.getInstance().raskaciSeSaServera();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormaGlavna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbPrikaziKatalog;
    private javax.swing.JButton jbPrikaziNarudzbenice;
    private javax.swing.JButton jbPrikaziRacune;
    // End of variables declaration//GEN-END:variables
}
