/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormaKatalog.java
 *
 * Created on May 27, 2010, 8:39:33 PM
 */

package com.cometoin.forme;

import java.util.LinkedList;
import java.util.List;

import javax.swing.ListSelectionModel;

import com.cometoin.domenskeKlase.Proizvod;
import com.cometoin.forme.komponente.KatalogTableModel;
import com.cometoin.klasaZaKomunikaciju.KlasaZaKomunikacijuKlijent;
import com.cometoin.kontrolerKorisnickogInterfejsa.KontrolerFormeKatalog;

/**
 *
 * @author user
 */
public class FormaKatalog extends javax.swing.JDialog {
    KontrolerFormeKatalog kfk;
    List listaProizvoda;
    /** Creates new form FormaKatalog */
    public FormaKatalog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaProizvoda = KlasaZaKomunikacijuKlijent.getInstance().vratiProizvode(new Proizvod());
        jtKatalog.setModel(new KatalogTableModel(listaProizvoda));
        jtKatalog.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        kfk = new KontrolerFormeKatalog();
        this.setTitle("Katalog");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtKatalog = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbDodajNoviProizvod = new javax.swing.JButton();
        jbObrisiProizvod = new javax.swing.JButton();
        jbIzmeniproizvod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbPronadji = new javax.swing.JButton();
        jtfPronadji = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtKatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtKatalog);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbDodajNoviProizvod.setText("Dodaj novi proizvod");
        jbDodajNoviProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDodajNoviProizvodActionPerformed(evt);
            }
        });

        jbObrisiProizvod.setText("Obrisi proizvod");
        jbObrisiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObrisiProizvodActionPerformed(evt);
            }
        });

        jbIzmeniproizvod.setText("izmeni proizvod");
        jbIzmeniproizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIzmeniproizvodActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv proizvoda: ");

        jbPronadji.setText("Ponadji");
        jbPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPronadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPronadji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jbDodajNoviProizvod)
                .addGap(18, 18, 18)
                .addComponent(jbIzmeniproizvod)
                .addGap(18, 18, 18)
                .addComponent(jbObrisiProizvod)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbObrisiProizvod)
                    .addComponent(jbIzmeniproizvod)
                    .addComponent(jbDodajNoviProizvod)
                    .addComponent(jLabel1)
                    .addComponent(jtfPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPronadji))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-886)/2, (screenSize.height-501)/2, 886, 501);
    }// </editor-fold>//GEN-END:initComponents

    private void jbIzmeniproizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIzmeniproizvodActionPerformed
        kfk.izmeniProizvod(jtKatalog,listaProizvoda);
    }//GEN-LAST:event_jbIzmeniproizvodActionPerformed

    private void jbObrisiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObrisiProizvodActionPerformed
       kfk.obrisiProizvod(jtKatalog,listaProizvoda);
    }//GEN-LAST:event_jbObrisiProizvodActionPerformed

    private void jbDodajNoviProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDodajNoviProizvodActionPerformed
        kfk.dodajProizvod(jtKatalog,listaProizvoda);
}//GEN-LAST:event_jbDodajNoviProizvodActionPerformed

    private void jbPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPronadjiActionPerformed
        kfk.pronadjiProizvode(jtfPronadji,jtKatalog,listaProizvoda);
    }//GEN-LAST:event_jbPronadjiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDodajNoviProizvod;
    private javax.swing.JButton jbIzmeniproizvod;
    private javax.swing.JButton jbObrisiProizvod;
    private javax.swing.JButton jbPronadji;
    private javax.swing.JTable jtKatalog;
    private javax.swing.JTextField jtfPronadji;
    // End of variables declaration//GEN-END:variables

}
