/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormaRacun.java
 *
 * Created on Jun 9, 2010, 10:23:38 PM
 */
package com.cometoin.forme;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;

import com.cometoin.domenskeKlase.Proizvod;
import com.cometoin.domenskeKlase.Racun;
import com.cometoin.domenskeKlase.StavkaRacuna;
import com.cometoin.forme.komponente.StavkaTableModel;
import com.cometoin.kontrolerKorisnickogInterfejsa.KontrolerFormeRacun;

/**
 *
 * @author user
 */
public class FormaRacun extends javax.swing.JDialog implements ActionListener {

    KontrolerFormeRacun kfr;
    Racun racun;
    //1 - dodaj novu narudzbenicu; 2 - zapamti izmenjenu narudzbenicu
    int mod;

    /** Creates new form FormaRacun */
    public FormaRacun(java.awt.Frame parent, boolean modal, int mod, Racun racun) {
        super(parent, modal);
        initComponents();
        this.mod = mod;
        this.racun = racun;
        jtStavkeRacuna.setModel(new StavkaTableModel());
        kfr = new KontrolerFormeRacun();
        jcbProizvodi = napraviJCBProizvodi();
        srediFormu(mod);
        this.setTitle("Racun");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtStavkeRacuna = new javax.swing.JTable();
        jbDodajNovuStavku = new javax.swing.JButton();
        jbZapamti = new javax.swing.JButton();
        jbOdustani = new javax.swing.JButton();
        jbObrisiStavku = new javax.swing.JButton();
        jbObradi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtfObradjen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfSifraRacuna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDatum = new javax.swing.JTextField();
        jtfPartner = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtStavkeRacuna.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtStavkeRacunaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtStavkeRacuna);

        jbDodajNovuStavku.setText("Dodaj novu stavku");
        jbDodajNovuStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDodajNovuStavkuActionPerformed(evt);
            }
        });

        jbZapamti.setText("Zapamti");
        jbZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbZapamtiActionPerformed(evt);
            }
        });

        jbOdustani.setText("Odustani");
        jbOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOdustaniActionPerformed(evt);
            }
        });

        jbObrisiStavku.setText("Obrisi");
        jbObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObrisiStavkuActionPerformed(evt);
            }
        });

        jbObradi.setText("Obradi");
        jbObradi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObradiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o racunu"));

        jLabel4.setText("Obradjen");

        jLabel3.setText("Partner:");

        jLabel2.setText("Datum:");

        jLabel1.setText("Sifra racuna");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfObradjen)
                    .addComponent(jtfSifraRacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfPartner)
                    .addComponent(jtfDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfSifraRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtfObradjen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbDodajNovuStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbObrisiStavku)
                        .addGap(87, 87, 87)
                        .addComponent(jbObradi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(jbOdustani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDodajNovuStavku)
                    .addComponent(jbObrisiStavku)
                    .addComponent(jbZapamti)
                    .addComponent(jbOdustani)
                    .addComponent(jbObradi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-771)/2, (screenSize.height-551)/2, 771, 551);
    }// </editor-fold>//GEN-END:initComponents

    private void jtStavkeRacunaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtStavkeRacunaPropertyChange
        int red = jtStavkeRacuna.getSelectedRow();
        int kolona = jtStavkeRacuna.getSelectedColumn();
        if (red != -1 && kolona == 4) {
            double cena = Double.parseDouble(jtStavkeRacuna.getValueAt(red, 3) + "");
            double kolicina = Integer.parseInt(jtStavkeRacuna.getValueAt(red, 4) + "0") / 10;
            double suma = cena * kolicina;
            jtStavkeRacuna.setValueAt(suma, red, 5);
        }
}//GEN-LAST:event_jtStavkeRacunaPropertyChange

    private void jbDodajNovuStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDodajNovuStavkuActionPerformed
        kfr.dodajStavku(jtStavkeRacuna, jcbProizvodi);
}//GEN-LAST:event_jbDodajNovuStavkuActionPerformed

    private void jbZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbZapamtiActionPerformed
        kfr.zapamtiRacun(jtfSifraRacuna, jtfDatum, jtfPartner, jtStavkeRacuna, racun, mod, this);
}//GEN-LAST:event_jbZapamtiActionPerformed

    private void jbOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOdustaniActionPerformed
        kfr.obrisiRacun(racun, mod, this);
}//GEN-LAST:event_jbOdustaniActionPerformed

    private void jbObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObrisiStavkuActionPerformed
        kfr.obrisiStavku(jtStavkeRacuna);
}//GEN-LAST:event_jbObrisiStavkuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        kfr.obrisiRacun(racun, mod, this);
    }//GEN-LAST:event_formWindowClosing

    private void jbObradiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObradiActionPerformed
        if (kfr.obradiRacun(racun,jbZapamti) == 0) {
            jtStavkeRacuna.setModel(new StavkaTableModel());
            srediFormu(mod);
        }
    }//GEN-LAST:event_jbObradiActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDodajNovuStavku;
    private javax.swing.JButton jbObradi;
    private javax.swing.JButton jbObrisiStavku;
    private javax.swing.JButton jbOdustani;
    private javax.swing.JButton jbZapamti;
    private javax.swing.JTable jtStavkeRacuna;
    private javax.swing.JTextField jtfDatum;
    private javax.swing.JTextField jtfObradjen;
    private javax.swing.JTextField jtfPartner;
    private javax.swing.JTextField jtfSifraRacuna;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JComboBox jcbProizvodi;

    private void srediFormu(int mod) {
        if (racun.isObradjen()) {
            jtfDatum.setEnabled(false);
            jtfPartner.setEnabled(false);
            jtfObradjen.setText("DA");
            jtfObradjen.setEnabled(false);
            jtStavkeRacuna.setEnabled(false);
            jbZapamti.setEnabled(false);
            jbObradi.setEnabled(false);
            jbDodajNovuStavku.setEnabled(false);
            jbObrisiStavku.setEnabled(false);
            jbOdustani.setEnabled(false);
        } else {
            jtfObradjen.setText("NE");
            jtfObradjen.setEnabled(false);
        }
        switch (mod) {
            case 1:
                jtfSifraRacuna.setText(racun.getSifra() + "");
                jtfSifraRacuna.setEnabled(false);
                break;
            case 2:
                jbZapamti.setText("Sacuvaj izmene");
                jtfDatum.setText(racun.getDatum());
                jtfPartner.setText(racun.getNazivPartnera());
                jtfSifraRacuna.setText(racun.getSifra() + "");
                jtfSifraRacuna.setEditable(false);
                kfr = new KontrolerFormeRacun(racun);

                for (int i = 0; i < racun.getStavkeRacuna().size(); i++) {
                    StavkaRacuna sr = ((StavkaRacuna) racun.getStavkeRacuna().get(i));
                    JComboBox jcbProiz = napraviJCBProizvodi();
                    int indexProiz = vratiIndexZeljenogProizvoda(jcbProiz, sr.getSifraProizvoda());
                    Proizvod p = (Proizvod) jcbProiz.getItemAt(indexProiz);
                    jcbProiz.setSelectedIndex(indexProiz);
                    sr.setNazivProizvoda(p.getNaziv());
                    sr.setCenaProizvoda(p.getCena());

                    System.out.println(p.vratiPodatkeKaoString());
                    Vector v = new Vector();
                    v.add(sr.getRedniBroj());
                    v.add(sr.getNazivProizvoda());
                    v.add(sr.getSifraProizvoda());
                    v.add(sr.getCenaProizvoda());
                    v.add(sr.getKolicina());
                    System.out.println(sr.getCenaProizvoda() * sr.getKolicina());
                    v.add(sr.getCenaProizvoda() * sr.getKolicina());
                    ((StavkaTableModel) jtStavkeRacuna.getModel()).addRow(v);

                    TableColumn tc = jtStavkeRacuna.getColumnModel().getColumn(1);

                    tc.setCellEditor(new DefaultCellEditor(jcbProiz));
                }
                break;
            default:
                jbZapamti.setText("Sacuvaj.");
                break;
        }
    }

    private JComboBox napraviJCBProizvodi() {
        JComboBox comboBox = new JComboBox();
        List proizvodi = kfr.vratiSveProizvode();
        Iterator it = proizvodi.iterator();
        while (it.hasNext()) {
            Proizvod p = (Proizvod) it.next();
            comboBox.addItem(p);
        }
        comboBox.addActionListener(this);
        return comboBox;
    }

    public int vratiIndexZeljenogProizvoda(JComboBox comboBox, int sifraProizvoda) {
        int brProizvoda = comboBox.getItemCount();
        for (int i = 0; i < brProizvoda; i++) {
            Proizvod p = (Proizvod) comboBox.getItemAt(i);
            if (p.getSifraProizvoda() == sifraProizvoda) {
                return i;
            }
        }
        return -1;
    }

    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JComboBox) {
            int kolona = jtStavkeRacuna.getSelectedColumn();
            int red = jtStavkeRacuna.getSelectedRow();
            if (kolona == 1) {//&& p != null) {
                Proizvod p = (Proizvod) ((StavkaTableModel) jtStavkeRacuna.getModel()).getValueAt(red, kolona);
                System.out.println(p.vratiPodatkeKaoString());
                ((StavkaTableModel) jtStavkeRacuna.getModel()).setValueAt(p.getSifraProizvoda(), red, kolona + 1);
                ((StavkaTableModel) jtStavkeRacuna.getModel()).setValueAt(p.getCena(), red, kolona + 2);
                double cena = Double.parseDouble(jtStavkeRacuna.getValueAt(red, 3) + "");
                double kolicina = Integer.parseInt(jtStavkeRacuna.getValueAt(red, 4) + "0") / 10;
                double suma = cena * kolicina;
                jtStavkeRacuna.setValueAt(suma, red, 5);
            }
        }
    }
}
