/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Proizvod.java
 *
 * Created on May 21, 2010, 10:54:10 PM
 */
package com.cometoin.forme;

import com.cometoin.domenskeKlase.Proizvod;
import com.cometoin.kontrolerKorisnickogInterfejsa.KontrolerFormeProizvod;

/**
 *
 * @author user
 */
public class FormaProizvod extends javax.swing.JDialog {

    int mod;
    Proizvod proizvod;
    KontrolerFormeProizvod kkiProizvodForma;

    /** Creates new form Proizvod */
    public FormaProizvod(java.awt.Frame parent, boolean modal, int mod, Proizvod proizvod) {
        super(parent, modal);
        //1 - ako sacuvava novi proizvod 2 - ako izmenjuje proizvod proizvod
        this.mod = mod;
        this.proizvod = proizvod;
        initComponents();
        srediFormu(mod);
        kkiProizvodForma = new KontrolerFormeProizvod();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbOtkazi = new javax.swing.JButton();
        jtfKolicina = new javax.swing.JTextField();
        jtfCena = new javax.swing.JTextField();
        jtfDobavljac = new javax.swing.JTextField();
        jtfOpis = new javax.swing.JTextField();
        jtfNaziKnjige = new javax.swing.JTextField();
        jbSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proizvod");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o knjizi"));

        jLabel1.setText("Naziv knjige");

        jLabel2.setText("Dobavljac");

        jLabel3.setText("Opis");

        jLabel4.setText("Kolicina");

        jLabel5.setText("Cena");

        jbOtkazi.setText("Otkazi");
        jbOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOtkaziActionPerformed(evt);
            }
        });

        jbSacuvaj.setText("Sacuvaj");
        jbSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSacuvaj))
                    .addComponent(jtfCena)
                    .addComponent(jtfKolicina)
                    .addComponent(jtfNaziKnjige)
                    .addComponent(jtfDobavljac)
                    .addComponent(jtfOpis, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jtfNaziKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSacuvaj)
                            .addComponent(jbOtkazi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-388)/2, (screenSize.height-277)/2, 388, 277);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSacuvajActionPerformed
        kkiProizvodForma.sacuvajProizvod(jtfNaziKnjige, jtfDobavljac, jtfOpis, jtfKolicina, jtfCena, proizvod, mod,this);
    }//GEN-LAST:event_jbSacuvajActionPerformed

    private void jbOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbOtkaziActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbOtkazi;
    private javax.swing.JButton jbSacuvaj;
    private javax.swing.JTextField jtfCena;
    private javax.swing.JTextField jtfDobavljac;
    private javax.swing.JTextField jtfKolicina;
    private javax.swing.JTextField jtfNaziKnjige;
    private javax.swing.JTextField jtfOpis;
    // End of variables declaration//GEN-END:variables

    private void srediFormu(int mod) {
        switch (mod) {
            case 1:
                break;
            case 2:
                jbSacuvaj.setText("Sacuvaj izmene");
                jtfNaziKnjige.setText(proizvod.getNaziv());
                jtfDobavljac.setText(proizvod.getDobavljac());
                jtfKolicina.setText(proizvod.getKolicina()+"");
                jtfOpis.setText(proizvod.getOpis());
                jtfCena.setText(proizvod.getCena()+"");
                break;
            default:
                jbSacuvaj.setText("Sacuvaj.");
                break;
        }
    }
}
